name: CI

on:
  workflow_dispatch:
  push:

jobs:
  check-format:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install libraries for clang-format to work
      run: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh all
    - name: Check formatting matches clang-format for CPU0
      run: ./scripts/clang-format -version && bash ./scripts/check-format0.sh
    - name: Check formatting matches clang-format for CPU1
      run: ./scripts/clang-format -version && bash ./scripts/check-format1.sh
